export const myProjects = [
    {
      id : 1,
      projectTitle: "Booki project",
      category: ["HTML & CSS"],
      imgPath: "./images/Booki.png",
      github: "https://github.com/anissafia90/Booki",
      link:"https://anissafia90.github.io/Booki/",
    },
    { 
      id : 2,
      projectTitle: "react project",
      category: ["react"],
      imgPath: "./images/calculator.png",
      github: "https://github.com/anissafia90/calculator",
      link:"https://anissafia90.github.io/calculator/",
    },
    {
      id : 3,
      projectTitle: "Ecommerce project",
      category: ["react"],
      imgPath: "./images/React_ecomm.png",
      github: "",
      link:"https://condescending-edison-9f7741.netlify.app/?fbclid=IwAR3YOLg0zzBnb1JUg5pp07I5WBGD9Z15HToRm_M9EB-7ztTfYJ9wHgKpmkI",
    },
    {
      id : 4,
    projectTitle: "recipe page main project", 
    category: ["HTML & CSS"], 
    imgPath: "./images/recipe-page-main.png " ,
    github: "https://github.com/anissafia90/recipe-page-main",
    link:"https://anissafia90.github.io/recipe-page-main/",
    },
    {
      id : 5,
      projectTitle: "Restaurant project",
      category: ["HTML & CSS"],
      imgPath: "./images/React_restaurant.png",
      github: "",
    link:"https://heuristic-panini-7d7a17.netlify.app/index.html",
    },
    {
      id : 6, 
    projectTitle: "Profile card project", 
    category: ["HTML & CSS"], 
    imgPath: "./images/Profile-card.png" ,
    github: "https://github.com/anissafia90/Front_end_mentor_01",
    link:"https://anissafia90.github.io/Front_end_mentor_01/",
  },
  
    {
      id : 7,
      projectTitle: "landing Page Airpods project",
      category: ["js"],
      imgPath: "./images/landing_page.png",
      github: "https://github.com/anissafia90/Landing_pageLanding_page",
      link:"https://anissafia90.github.io/Landing_pageLanding_page/",
    },
    {
      id : 8,
      projectTitle: "Le monde en noir & blanc project",
      category: ["js"],
      imgPath: "./images/Le monde en noir & blanc.png",
      github: "https://github.com/anissafia90/Landing_pageLanding_page",
      link:"https://anissafia90.github.io/Landing_pageLanding_page/",
    },
    
    {
      id : 9,
      projectTitle: "registre form project",
      category: ["react"],
      imgPath: "./images/registre_form.png",
      github: "https://github.com/anissafia90/Registration-Form-using-React",
      link:"https://anissafia90.github.io/Registration-Form-using-React/",
    },
    {
      id : 10,
      projectTitle: "results summary component project",
      category: ["HTML & CSS"],
      imgPath: "./images/results-summary-component.png",
      github: "https://github.com/anissafia90/results-summary-component",
      link:"https://anissafia90.github.io/results-summary-component/",
    },
    {
      id : 11,
      projectTitle: "faq-accordion-main",
      category: ["js"],
      imgPath: "./images/faq-accordion-main.png",
      github: "https://github.com/anissafia90/faq-accordion-main",
      link:"https://anissafia90.github.io/faq-accordion-main/",
    },
    {
      id : 12,
      projectTitle: "E-commerce-product-page",
      category: ["js"],
      imgPath: "./images/E-commerce-product-page.png",
      github: "https://github.com/anissafia90/E-commerce-product-page",
      link:"https://anissafia90.github.io/E-commerce-product-page/",
    },
    {
      id : 13,
      projectTitle: "zaineb Sud",
      category: ["wordpress"],
      imgPath: "",
      github: "#",
      link:"https://zaineb-sud.me/",
    },
    {
      id : 14,
      projectTitle: "weather-app",
      category: ["react"],
      imgPath: "",
      github: "https://github.com/anissafia90/Weather-Application",
      link:"https://weather-app-anis.netlify.app/",
    },
  ];
